name: CI - Build, Lint, and Type Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rspec:
    uses: ./.github/workflows/rspec.yml
    secrets: inherit
  build-and-check:
    runs-on: ubuntu-latest
    env:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    steps:
      - name: display
        run: |
          echo "$GOOGLE_MAPS_API_KEY" | awk '$1=$1' FS= OFS=" "

          touch .env
          echo GOOGLE_MAPS_API_KEY = $GOOGLE_MAPS_API_KEY >> .env

          cat .env | awk '$1=$1' FS= OFS=" "
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run format

      - name: Build app
        run: npm run build
